import json
import pandas as pd
import os
from datetime import datetime

try:
    from rust_parser import parse_evtx_to_json
except ImportError:
    def parse_evtx_to_json(path): return "[]"

class LogEngine:
    def __init__(self):
        self.current_data = pd.DataFrame(columns=["TS", "Lvl", "Src", "ID", "Summary", "Msg"])

    def load_logs(self, file_paths):
        all_events = []
        for path in file_paths:
            if not os.path.exists(path): continue
            try:
                raw_json = parse_evtx_to_json(path)
                events = json.loads(raw_json)
                for event in events:
                    ev_obj = event.get("Event", {})
                    system = ev_obj.get("System", {})
                    
                    # Timestamp
                    time_attr = system.get("TimeCreated", {}).get("#attributes", {})
                    raw_ts = time_attr.get("SystemTime", "N/A")
                    ts = raw_ts.replace("T", " ").split(".")[0] if raw_ts != "N/A" else "N/A"
                    
                    # Origen y ID
                    src = system.get("Provider", {}).get("#attributes", {}).get("Name", "System")
                    raw_id = system.get("EventID", "0")
                    e_id = str(raw_id.get("#text", raw_id)) if isinstance(raw_id, dict) else str(raw_id)
                    
                    # Nivel
                    lvl_map = {"1":"CRITICAL", "2":"ERROR", "3":"WARNING", "4":"INFO", "0":"INFO"}
                    lvl = lvl_map.get(str(system.get("Level")), "INFO")
                    
                    # Resumen
                    edata = ev_obj.get("EventData", {})
                    summary = str(edata)[:200] if edata else f"Event {e_id} generated by {src}"

                    all_events.append({
                        "TS": ts, "Lvl": lvl, "Src": src, "ID": e_id,
                        "Summary": summary, "Msg": json.dumps(event, indent=2)
                    })
            except Exception as e:
                print(f"Error procesando archivo: {e}")
        
        if all_events:
            new_df = pd.DataFrame(all_events)
            self.current_data = pd.concat([self.current_data, new_df], ignore_index=True)
            self.current_data['dt_tmp'] = pd.to_datetime(self.current_data['TS'], errors='coerce')
            self.current_data = self.current_data.sort_values('dt_tmp').drop(columns=['dt_tmp'])

    def get_summary(self):
        if self.current_data.empty: return {"total": 0, "errors": 0, "warnings": 0}
        return {
            "total": len(self.current_data),
            "errors": len(self.current_data[self.current_data["Lvl"].isin(["ERROR", "CRITICAL"])]),
            "warnings": len(self.current_data[self.current_data["Lvl"] == "WARNING"])
        }

    def get_filtered_data(self, level=None):
        df = self.current_data
        if level:
            if level == "ERROR":
                df = df[df["Lvl"].isin(["ERROR", "CRITICAL"])]
            else:
                df = df[df["Lvl"] == level]
        return df

    def filter_by_time(self, df, start_str, end_str):
        if df.empty: return df
        try:
            start_dt = pd.to_datetime(start_str)
            end_dt = pd.to_datetime(end_str)
            temp_df = df.copy()
            temp_df['dt_obj'] = pd.to_datetime(temp_df['TS'], errors='coerce')
            mask = (temp_df['dt_obj'] >= start_dt) & (temp_df['dt_obj'] <= end_dt)
            return temp_df[mask].drop(columns=['dt_obj'])
        except:
            return df

    def search_data(self, df, query):
        if not query or df.empty: return df
        q = query.lower()
        mask = (df['Src'].str.lower().str.contains(q) | 
                df['ID'].str.lower().str.contains(q) | 
                df['Summary'].str.lower().str.contains(q))
        return df[mask]

    def get_stats_from_df(self, df):
        if df.empty: return []
        counts = df["ID"].value_counts().head(20)
        return [{"ID": k, "Count": v} for k, v in counts.items()]

    def get_burst_stats(self, df_input=None, window_seconds=60):
        df_base = df_input if df_input is not None else self.current_data
        if df_base.empty: return [], "TOP EVENT IDs", df_base
        
        df = df_base.copy()
        df['dt'] = pd.to_datetime(df['TS'], errors='coerce')
        df = df.dropna(subset=['dt']).sort_values('dt').set_index('dt')
        
        burst_group = df.resample(f'{window_seconds}s').size()
        if burst_group.empty: return [], "TOP EVENT IDs", df_base
        
        peak_time = burst_group.idxmax()
        peak_count = burst_group.max()
        end_time = peak_time + pd.Timedelta(seconds=window_seconds)
        
        burst_df = df[(df.index >= peak_time) & (df.index < end_time)].reset_index().drop(columns=['dt'])
        stats = self.get_stats_from_df(burst_df)
        title = f"RAFAGA DE {window_seconds} SEG: {peak_count} logs @ {peak_time.strftime('%H:%M:%S')}"
        return stats, title, burst_df